parameters:
- name: SkipTests
  type: boolean
  default: true
steps:
- powershell: .Tests/Invoke-Pester.ps1
  displayName: "Run Pester"
  failOnStderr: true
  continueOnError: true
  condition: eq('${{ parameters.SkipTests }}', false)
- task: ArchiveFiles@2
  displayName: 'Archive files Functions'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(PSFunctionFolderName)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(PSFunctionFolderName)/$(Build.BuildId).zip
    replaceExistingArchive: true
- publish: $(Build.ArtifactStagingDirectory)
  artifact: dropBackupFunctionApp