trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - bugfix/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'windows-latest'

parameters:
- name: SkipTests
  type: boolean
  default: true

variables:
  PSFunctionFolderName: Function
# abc
# some changes
stages:
  - stage: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) # Create builds only from the main branch
    jobs:
      - job: BuildJob
        steps:
          - template: templates/build.yml